version: '3.0'
services:
  kafka:
    image: wurstmeister/kafka:1.0.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "ticket:1:1"
    ports:
      - "9092:9092"
    volumes:
      - /tmp/docker-compose/cenylcz-gateway/kafka/:/kafka/
  zookeeper:
    image: zookeeper:3.4.11
    ports:
      - "2181:2181"