apiVersion: v1
kind: Service
metadata:
  name: {{ include "cenylcz-gateway.fullname" . }}
  labels:
    {{- include "cenylcz-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: {{ .Values.container.name }}
  selector:
    {{- include "cenylcz-gateway.selectorLabels" . | nindent 4 }}
